[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mesh2irc"
version = "0.2"
authors = [
    { name = "Drew Gochenaur" }
]
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=5.0",
    "platformdirs>=2.3.6",
    "irc>=20.5.0",
    "matrix-nio",
    "pydle",
    "meshcore"
]

[project.scripts]
mesh2chat = "mesh2irc.mesh2chat:main"
irc-server = "mesh2irc.irc.server:main"
matrix-bridge = "mesh2irc.matrix.bridge:main"
matrix-new-user = "mesh2irc.matrix.new_user:main"
matrix-app = "mesh2irc.matrix.app:main"
matrix-admin-cli = "mesh2irc.matrix.admincli:main"

[tool.black]
line-length = 120

[tool.pyright]
typeCheckingMode = "strict"
reportMissingTypeStubs = "none"
include = ["src"]
